//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceProject.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Driver
    {
        public int Id { get; set; }
        public Nullable<int> StateId { get; set; }
        public string LicenseNo { get; set; }
        public string Status { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public string MaritalStatus { get; set; }
        public string HomeType { get; set; }
        public string HomeStatusType { get; set; }
        public string Education { get; set; }
        public string Occupation { get; set; }
        public Nullable<int> ApplicantId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
    
        public virtual Applicant Applicant { get; set; }
        public virtual State State { get; set; }
    }
}
