//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceProject.Models.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InsuranceDBEntities : DbContext
    {
        public InsuranceDBEntities()
            : base("name=InsuranceDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Applicant> Applicants { get; set; }
        public DbSet<Driver> Drivers { get; set; }
        public DbSet<Login> Logins { get; set; }
        public DbSet<State> States { get; set; }
        public DbSet<Vehical> Vehicals { get; set; }
        public DbSet<VehicleUse> VehicleUses { get; set; }
        public DbSet<VIN> VINs { get; set; }
    }
}
