//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceProject.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehical
    {
        public int Id { get; set; }
        public string VIN { get; set; }
        public Nullable<int> Year { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public string Ownership { get; set; }
        public Nullable<int> ApplicantId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> VehicleUseId { get; set; }
        public string VehicalUse { get; set; }
    
        public virtual Applicant Applicant { get; set; }
        public virtual VehicleUse VehicleUse { get; set; }
    }
}
